# Generated by Django 4.1.7 on 2023-04-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
